// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Translators.Database.Contexts;

#nullable disable

namespace Translators.Migrations
{
    [DbContext(typeof(TranslatorContext))]
    [Migration("20220607142201_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Translators.Database.Entities.BookEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("NameId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NameId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Translators.Database.Entities.CatalogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("BookId")
                        .HasColumnType("bigint");

                    b.Property<long>("NameId")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("NameId");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("Translators.Database.Entities.CategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("NameId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Translators.Database.Entities.LanguageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Translators.Database.Entities.LanguageValueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<long>("LanguageId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsMain");

                    b.HasIndex("LanguageId");

                    b.HasIndex("Value");

                    b.ToTable("LanguageValues");
                });

            modelBuilder.Entity("Translators.Database.Entities.PageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("CatalogId")
                        .HasColumnType("bigint");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CatalogId");

                    b.HasIndex("Number");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Translators.Database.Entities.ParagraphEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AnotherValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Number")
                        .HasColumnType("bigint");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Number");

                    b.HasIndex("PageId");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("Translators.Database.Entities.WordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<long>("ParagraphId")
                        .HasColumnType("bigint");

                    b.Property<long>("ValueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Index");

                    b.HasIndex("ParagraphId");

                    b.HasIndex("ValueId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Translators.Database.Entities.WordLetterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.HasIndex("WordId");

                    b.ToTable("WordLetterEntity");
                });

            modelBuilder.Entity("Translators.Database.Entities.WordRootEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.HasIndex("WordId");

                    b.ToTable("WordRootEntity");
                });

            modelBuilder.Entity("Translators.Database.Entities.BookEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.CategoryEntity", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Translators.Database.Entities.LanguageValueEntity", "Name")
                        .WithMany("Books")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Translators.Database.Entities.CatalogEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.BookEntity", "Book")
                        .WithMany("Catalogs")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Translators.Database.Entities.LanguageValueEntity", "Name")
                        .WithMany("Catalogs")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Translators.Database.Entities.CategoryEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.LanguageValueEntity", "Name")
                        .WithMany("Categories")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Name");
                });

            modelBuilder.Entity("Translators.Database.Entities.LanguageValueEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.LanguageEntity", "Language")
                        .WithMany("LanguageValues")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Translators.Database.Entities.PageEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.CatalogEntity", "Catalog")
                        .WithMany("Pages")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catalog");
                });

            modelBuilder.Entity("Translators.Database.Entities.ParagraphEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.PageEntity", "Page")
                        .WithMany("Paragraphs")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Translators.Database.Entities.WordEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.ParagraphEntity", "Paragraph")
                        .WithMany("Words")
                        .HasForeignKey("ParagraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Translators.Database.Entities.LanguageValueEntity", "Value")
                        .WithMany("Words")
                        .HasForeignKey("ValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paragraph");

                    b.Navigation("Value");
                });

            modelBuilder.Entity("Translators.Database.Entities.WordLetterEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.WordEntity", "Word")
                        .WithMany("WordLetters")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Translators.Database.Entities.WordRootEntity", b =>
                {
                    b.HasOne("Translators.Database.Entities.WordEntity", "Word")
                        .WithMany("WordRoots")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Translators.Database.Entities.BookEntity", b =>
                {
                    b.Navigation("Catalogs");
                });

            modelBuilder.Entity("Translators.Database.Entities.CatalogEntity", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("Translators.Database.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Translators.Database.Entities.LanguageEntity", b =>
                {
                    b.Navigation("LanguageValues");
                });

            modelBuilder.Entity("Translators.Database.Entities.LanguageValueEntity", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Catalogs");

                    b.Navigation("Categories");

                    b.Navigation("Words");
                });

            modelBuilder.Entity("Translators.Database.Entities.PageEntity", b =>
                {
                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("Translators.Database.Entities.ParagraphEntity", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("Translators.Database.Entities.WordEntity", b =>
                {
                    b.Navigation("WordLetters");

                    b.Navigation("WordRoots");
                });
#pragma warning restore 612, 618
        }
    }
}
